export const players = [
    { id : 1,
    name : "Lionel Messi",
    team : "Inter Miami",
    nationality : "Argentina",
    jerseyNumber : 10,
    age : 37,
    image : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkcNCjLQ4c_AEja3yXS4u5C3dYfFaPHSm45w&s",
},
{ id : 1,
    name : "Lamine Yamal",
    team : "Fc Barcelona",
    nationality : "Spain",
    jerseyNumber : 19,
    age : 17,
    image : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTv0Hpl4ay-5CL6RiS0zEDKn2j2SSq4nK_0oA&s" 
},
{ id : 1,
    name : "Pedri",
    team : "Fc Barcelona",
    nationality : "Spain",
    jerseyNumber : 8,
    age : 22,
    image : "https://www.fcbarcelona.com/photo-resources/2024/05/20/eaef37c6-8460-4aa0-842c-e14a6dced723/2024-05-19_FCBvsRAYO_135.JPG?width=1200&height=750" 
},
{ id : 1,
    name : "Cubarsi",
    team : "Fc Barcelona",
    nationality : "Spain",
    jerseyNumber : 2,
    age : 17,
    image : "https://trendsports360.com/wp-content/uploads/2024/02/Pau-Cubarsi-Fc-Barcelone-Getty.jpg" 
},
]
export default players;